# Generated by Django 4.0.4 on 2022-05-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0004_rename_board_card_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
