# Generated by Django 4.0.4 on 2022-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0006_checklist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
