# Generated by Django 4.0.4 on 2022-05-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0007_checklistitem_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
