# Generated by Django 4.0.4 on 2022-05-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0008_alter_card_card_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('card_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_boards.card')),
            ],
        ),
    ]
