# Generated by Django 4.0.4 on 2022-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0009_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_title',
            field=models.BooleanField(default=False),
        ),
    ]
