# Generated by Django 4.0.4 on 2022-05-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0010_alter_label_label_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label_title',
            new_name='label_selected',
        ),
    ]
