# Generated by Django 4.0.4 on 2022-05-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0011_rename_label_title_label_label_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
