# Generated by Django 4.0.4 on 2022-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0013_card_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
