# Generated by Django 4.0.4 on 2022-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0014_alter_card_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='card_order',
            field=models.TextField(blank=True),
        ),
    ]
