# Generated by Django 4.0.4 on 2022-06-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0015_list_card_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='list_order',
            field=models.TextField(blank=True),
        ),
    ]
