# Generated by Django 4.0.4 on 2022-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0016_board_list_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date_completed',
            field=models.BooleanField(default=False),
        ),
    ]
