# Generated by Django 4.0.5 on 2022-06-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0022_board_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_color',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
