# Generated by Django 4.0.5 on 2022-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0023_alter_board_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='background_color_code',
            field=models.CharField(default='#00FF00', max_length=200),
            preserve_default=False,
        ),
    ]
