# Generated by Django 4.0.5 on 2022-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0024_boardmembership_background_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_custom_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
