# Generated by Django 4.0.5 on 2022-07-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0025_label_label_custom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_custom_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
