# Generated by Django 4.0.5 on 2022-07-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_boards', '0026_alter_label_label_custom_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='label_selected',
        ),
        migrations.AddField(
            model_name='label',
            name='board',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='trello_boards.board'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CardLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_boards.card')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_boards.label')),
            ],
        ),
    ]
